[serverConfiguration]
network = "tcp"
listenAddress = ":8080"
h2cEnabled = false
context = "/rpi_api/v1"

[profilingConfiguration]
enabled = true
listenAddress = ":8081"

[commandConfiguration]
maxConcurrentCommands = 10
requestTimeoutDuration = "2s"
semaphoreAcquireTimeoutDuration = "200ms"
commands = [
    { id = "cpuinfo", description = "cpuinfo", command = "/bin/cat", args = [
        "/proc/cpuinfo",
    ] },
    { id = "df", description = "df", command = "/bin/df", args = [
        "-h",
    ] },
    { id = "envstat", description = "envstat", command = "/usr/sbin/envstat" },
    { id = "git_log", description = "git log", command = "/usr/pkg/bin/git", args = [
        "log",
        "-1",
    ] },
    { id = "ifconfig", description = "ifconfig", command = "/sbin/ifconfig" },
    { id = "netstat_an", description = "netstat -an", command = "/usr/bin/netstat", args = [
        "-a",
        "-n",
    ] },
    { id = "ntpq", description = "ntpq -pnw", command = "/usr/sbin/ntpq", args = [
        "-p",
        "-n",
        "-w",
    ] },
    { id = "sysctl_machdep", description = "sysctl machdep", command = "/sbin/sysctl", args = [
        "machdep",
    ] },
    { id = "top", description = "top", command = "/usr/bin/top", args = [
        "-b",
    ] },
    { id = "top_ores", description = "top -o res", command = "/usr/bin/top", args = [
        "-b",
        "-o",
        "res",
    ] },
    { id = "uptime", description = "uptime", command = "/usr/bin/uptime" },
    { id = "vmstat", description = "vmstat", command = "/usr/bin/vmstat" },
    { id = "w", description = "w", command = "/usr/bin/w" },
]
